### ISSUE TITLE
SNOW-521252: Multiple statements per API Call

### ISSUE THREAD

**Issue by jordantshaw** [snowflakedb/snowflake-connector-python#1015]
## What is the current behavior?
Currently multiple SQL statements are not supported for a single API call. If multiple SQL statements are included in a single call, the following error is thrown.

`Snowflake.connector.errors.ProgrammingError: Multiple SQL statements in a single API call are not supported; use one API call per statement instead.`

## What is the desired behavior?
Support multiple SQL Statements per API call.

## How would this improve `snowflake-connector-python`?
This would be extremely useful if variables are needed within a SQL statement.  This is also useful for creating and using temporary tables and temporary stages within your SQL statements without having to do multiple calls.

**Comment by sfc-gh-mkeller** [comment]
Let's review this ticket and prioritize it @sfc-gh-hkapre

**Comment by jordantshaw** [comment]
@sfc-gh-mkeller any updates on where this is on your priority, or when it might be added?

**Comment by kaxil** [comment]
This would be great for Airflow users who are using this connector via [`SnowflakeOperatorAsync`](https://astronomer-providers.readthedocs.io/en/stable/_api/astronomer/providers/snowflake/operators/snowflake/index.html#astronomer.providers.snowflake.operators.snowflake.SnowflakeOperatorAsync)

**Comment by mitch-tanney-coterie** [comment]
@sfc-gh-hkapre & @sfc-gh-jhollan, do either of you by chance have any updates to report on this issue? A status update on any development work and/or a priority update would be greatly appreciated whenever your schedules allow. We are currently leveraging the snowflake connector in a Databricks notebook, but we aren't able to return data currently as desired because our query uses multiple variables. We can retrieve data and then apply the variables in Python, but our preference would be to handle this in the query if possible.

**Comment by sfc-gh-mkeller** [comment]
#1281 👀
