### ISSUE TITLE
Python connector triggers MFA push notification

### ISSUE THREAD

**Issue by tuzonghua** [snowflakedb/snowflake-connector-python#105]
I have MFA enabled on my account. Every time I run a Python script that called the Snowflake module, it triggers a Duo Mobile push notification to approve. [This page](https://docs.snowflake.net/manuals/user-guide/security-mfa.html) seems to detail ways to connect using MFA, but doesn't mention Python. My assumption is that once authorized, I should be able to run my script multiple times within a given period without needing to approve every run.

Is there a way around this?

**Comment by smtakeda** [comment]
Actually the parameters are already explained in this page:
https://docs.snowflake.net/manuals/user-guide/python-connector-api.html#methods
I've asked the documentation team to update the MFA doc anyway.

About how MFA works, basically every connection requires the authentication, because no token is cached by default. However, there is a new feature under private preview will do the cache up to 4 hours. Please contact to the support to enable the id token cache feature so that the connection parameter can take:
```
session_parameters={"CLIENT_STORE_TEMPORARY_CREDENTIAL"}
```
v1.6.6 (to be released this week) or newer version of Python connector is recommended.
