### ISSUE TITLE
SNOW-679732: Please stop aggressively upper bounding cryptography

### ISSUE THREAD

**Issue by hauntsaninja** [snowflakedb/snowflake-connector-python#1284]
This is causing a lot of pain for users. See for example https://github.com/snowflakedb/snowflake-connector-python/issues/1259 and https://github.com/snowflakedb/snowflake-connector-python/issues/1118 (would love a release for https://github.com/snowflakedb/snowflake-connector-python/pull/1266 by the way :-) )

Here's a writeup about why always preemptively upper bounding is a bad idea: https://iscinumpy.dev/post/bound-version-constraints/

Even if you don't agree with that article, the upper bounding snowflake-connector-python does is still way too aggressive, given that cryptography promises API stability for three major versions: https://cryptography.io/en/stable/api-stability/

**Comment by ofek** [comment]
It's causing massive issues for us as well.

@keller00 WDYTA removing the cap?

**Comment by sfc-gh-mkeller** [comment]
> Even if you don't agree with that article, the upper bounding snowflake-connector-python does is still way too aggressive, given that cryptography promises API stability for three major versions: [cryptography.io/en/stable/api-stability](https://cryptography.io/en/stable/api-stability/)

I don't think that this makes pining any less of an issue, imagine that we are on `x.y.z`, the upper pins looks like `x+1.0.0` what happens if method `abc` was deprecated since `x-2.0.0`? This is not something that we can rely on without running our tests against the bumped dependency. This is what dependabot was supposed to help us with. I guess it's not currently working as we had hoped. I've filed a Jira for one of the team members to re-evaluate what's broken here [SNOW-683430](https://snowflakecomputing.atlassian.net/browse/SNOW-683430).
The other scenario is that we only pin an upper limit when we run into issues, unfortunately that'd lead to every version before the fixed version staying broken. So if I have a requirements file with `snowflake-connector-python==x.y.z` pin that will still be broken even if `x.y.z+1` had a more restrictive upper pin limit.

In general, our dependency policy is available [here](https://docs.snowflake.com/en/user-guide/python-connector-dependencies.html).
If we removed upper pin limit(s) that'd mean that we'd need to constantly check our CI reports and GitHub issues to see when something broke our Python driver.
It's true that this used to happen more in the past, we had to jump on very frequently over the weekends to figure out what dependency's release broke us, update pins and do an unscheduled release, but the possibility is still there as mistakes happen and most open-source projects release over the weekends.

From our perspective down-time for our users is unacceptable. We pin projects following SemVer according to its principles.

Now, is our policy perfect? Definitely not, [there are exceptions](https://github.com/snowflakedb/snowflake-connector-python/pull/621). I do believe that what we have now has accomplished what we were trying to do and that's to shield users from surprises.
I believe that there should be a second, less restrictive set of dependencies, could we add them with optional dependency groups? Would an open-source fork of the driver maintained by the community be a better way to do this? Maybe a fork that is automatically updated, patched and released by some CI?

I'm open to discuss options with you and help out from the team's side, but I believe that what we have now is beneficial to most of our users!

Could you please provide more context on what other dependency pins are causing headaches for you and why do you need the newer versions? I understand that we have fallen behind on `cryptography` and we'll address this issue for the future with the Jira I linked.

**Comment by alopezz** [comment]
We're also waiting for the release of #1266 in order to be able to update another important dependency without having to resort to patching.

> > Even if you don't agree with that article, the upper bounding snowflake-connector-python does is still way too aggressive, given that cryptography promises API stability for three major versions: [cryptography.io/en/stable/api-stability](https://cryptography.io/en/stable/api-stability/)
> 
> I don't think that this makes pining any less of an issue, imagine that we are on `x.y.z`, the upper pins looks like `x+1.0.0` what happens if method `abc` was deprecated since `x-2.0.0`? This is not something that we can rely on without running our tests against the bumped dependency. 

According to [`cryptography`'s deprecation policy](https://cryptography.io/en/stable/api-stability/#deprecation), features on their way to deprecation will emit `UserWarning`s. Therefore, it should be easy enough to check for the presence of those warnings when testing the current version of `snowflake-connector`, and bump the cap according to that policy.

> In general, our dependency policy is available [here](https://docs.snowflake.com/en/user-guide/python-connector-dependencies.html).

There's a note on that policy that I think is relevant here:

> These rules are based on the assumption that all packages, including the Snowflake Connector for Python, follow the [semantic versioning guidelines](https://semver.org/).

I don't think `cryptography` follows semver, since they bump the major version with every feature release.

> From our perspective down-time for our users is unacceptable. 

I understand this, though I believe it's easier from the user's perspective to work around a loose bound than a tight bound. A tight bound may prevent users from getting important (sometimes critical), security-related upgrades on other packages used by the same application. The only workaround for this is often to patch things like `setup.py`, which is messy. A workaround for a loose bound is as simple as manually adding a tighter bound wherever the user is specifying their dependencies. 

Also, applications should typically be expected to have their requirements pinned or tightly bound anyway, which protects them from becoming broken because of a third-party releasing a new version of a package.

> Now, is our policy perfect? Definitely not, [there are exceptions](https://github.com/snowflakedb/snowflake-connector-python/pull/621).

Given that an exception was given already for a dependency on the grounds of it not following SemVer, why not do the same with `cryptography`, which doesn't follow it either?

**Comment by sfc-gh-mkeller** [comment]
> According to [cryptography's deprecation policy](https://cryptography.io/en/stable/api-stability/#deprecation), features on their way to deprecation will emit UserWarnings. Therefore, it should be easy enough to check for the presence of those warnings when testing the current version of snowflake-connector, and bump the cap according to that policy.

In that case we could turn warnings into errors during test runs. According to [the docs](https://docs.pytest.org/en/7.1.x/how-to/capture-warnings.html?highlight=warnings%20errors#controlling-warnings) this might be as easy as adding to [tox.ini](https://github.com/snowflakedb/snowflake-connector-python/blob/5a4e7a6a3b1a39a9e3cf6be6d16655f435d62e00/tox.ini#L150):
```
filterwarnings =
    error::UserWarning
```

I'll schedule someone to test this out! I'd be okay loosening the `cryptography`'s pin to 3 major versions if we could error on `UserWarning`s. However; I do think that we need to get dependabot working again, otherwise we are going to fall behind eventually.
What do you think @sfc-gh-aling @sfc-gh-yixie @sfc-gh-sfan

**Comment by hauntsaninja** [comment]
Thank you for being open to this!

I think turning warnings into errors and loosening to `<n+3` seems like a win-win situation (assuming you remember to keep bumping it / dependabot knows to keeps the n+3 going)

An automatically but officially maintained fork with less restrictive upper bounds is an interesting idea. But it gets a little tricky if snowflake-connector-python is ever a transitive dependency (e.g. we use snowflake-sqlalchemy).

> Could you please provide more context on what other dependency pins are causing headaches for you and why do you need the newer versions?

With snowflake-connector-python, it's mainly been cryptography (hence the title of this issue), although I seem to recall some issue with pyarrow at some point.
As for why we need newer versions? I'm not sure it's snowflake-connector-python's place to be asking this, especially for security sensitive dependencies :-) Usually because newer versions [fix some issue for us or for a dependency of ours](https://iscinumpy.dev/post/bound-version-constraints/#code-does-not-work-forever). In large Python environments, with several hundred dependencies, just updating one or two things [can rapidly snowball](https://iscinumpy.dev/post/bound-version-constraints/#it-doesnt-scale) because of preemptive upper bounds (let alone e.g. trying to do all the upgrades you need to get to a new version of Python).

(I'll also note dependabot isn't a magic bullet and that there's also a sort of tragedy of the commons situation. If say, your dependencies like pyopenssl took your lead and upper bounded cryptography, dependabot PRs wouldn't actually do anything, because at installation time, pip would just backsolve to whatever pyopenssl asked for, and your CI would still look green, right up until pyopenssl made a patch version release bumping their cryptography upper bound. And no, the solution to that isn't pinning pyopenssl exactly ;-) )

**Comment by malduarte** [comment]
What  @hauntsaninja said! Also, it would be helpful to get some release date guidance. The latest released version at the moment is v2.8.0 and is preventing upgrade to the latest [cloud-composer release](https://cloud.google.com/composer/docs/concepts/versioning/composer-versions) as it depends on cryptography 37.0.4. I've noticed that main has already the necessary changes.

**Comment by ofek** [comment]
Any update on this?

**Comment by sfc-gh-aling** [comment]
I'll echo that n+3 is a win-win solution here after discussion with @sfc-gh-mkeller.

We want users who pin their connector in their environment to have a compatible cryptography, also we will take advantage of the dependentbot to help us automatically bumping the version.

We have a PR out to loosen the cryptography version to latest + 3 and we will treat any cryptography UserWarning as a warning to monitor potential API changes.
