### ISSUE TITLE
SNOW-689565: Snowflake Connector unable to upload file from Lambda Ephemeral Storage

### ISSUE THREAD

**Issue by ihatec0d1ng** [snowflakedb/snowflake-connector-python#1320]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

3.9
2. What operating system and processor architecture are you using?

   Windows-10-10.0.19041-SP0

3. What are the component versions in the environment (`pip freeze`)?
asn1crypto==1.5.1
atomicwrites==1.4.0
attrs==21.4.0
black==22.6.0
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
charset-normalizer==2.0.12
click==8.1.3
colorama==0.4.5
conda==4.7.10
conda-package-handling==1.3.11
coverage==6.4.1
cryptography==3.4.8
dnspython==2.1.0
idna==2.8
importlib-metadata==4.12.0
iniconfig==1.1.1
libarchive-c==2.8
menuinst==1.4.16
mypy-extensions==0.4.3
oscrypto==1.2.1
packaging==21.3
pathspec==0.9.0
platformdirs==2.5.2
pluggy==1.0.0
py==1.11.0
pycosat==0.6.3
pycparser==2.19
pycryptodomex==3.14.1
PyJWT==2.3.0
pymongo==4.0.1
pyOpenSSL==19.0.0
pyparsing==3.0.9
PySocks==1.7.0
pytest==7.1.2
pytz==2022.1
pywin32==223
requests==2.22.0
ruamel_yaml==0.15.46
six==1.12.0
snowflake==0.0.3
snowflake-connector-python==2.7.0
tomli==2.0.1
tqdm==4.32.1
typed-ast==1.5.4
typing_extensions==4.3.0
urllib3==1.24.2
win-inet-pton==1.1.0
wincertstore==0.2
zipp==3.8.0
   

4. What did you do?

Using snowflake.connector to read a file stored in aws lambda ephemeral storage  (/tmp/<filename>) and put in snowflake using - 
"PUT file:///tmp/filename @%snowflake-table-stage "

5. What did you expect to see?

This should read the file from the lambda ephemeral storage (/tmp directory) and load it to snowflake. However, the code is automatically detecting that it's triggered from AWS and it's trying to access the file in S3 bucket by default. and hence failing to upload.
The code is running "remote_storage_util.py" when it should actually run "local_util.py".

6. Can you set logging to DEBUG and collect the logs?

  [ERROR]	2022-11-04T19:59:03.984Z	850bd5de-7b5d-4c1c-a3b2-7ceda3a4bed8	Failed to upload a file: file=/tmp/csv_uploading.csv, real file=/tmp/csv_uploading.csv
Traceback (most recent call last):
  File "/opt/python/lib/python3.8/site-packages/snowflake/connector/file_transfer_agent.py", line 437, in upload_one_file
    storage_client.upload_one_file_with_retry(meta)
  File "/opt/python/lib/python3.8/site-packages/snowflake/connector/remote_storage_util.py", line 257, in upload_one_file_with_retry
    SnowflakeRemoteStorageUtil.upload_one_file(meta)
  File "/opt/python/lib/python3.8/site-packages/snowflake/connector/remote_storage_util.py", line 149, in upload_one_file
    raise Exception(msg)
Exception: Unknown Error in uploading a file: /tmp/tmpe7ahwt_g/csv_uploading.csv#kt_9a3iy

[ERROR] OperationalError: 253003: Unknown Error in uploading a file: /tmp/tmpe7ahwt_g/csv_uploading.csv#kt_9a3iy, file=/tmp/csv_uploading.csv, real file=/tmp/csv_uploading.csv
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 65, in lambda_handler
    cs.execute("PUT file:///tmp/csv_uploading.csv @%u2_clmnt_sql_list_dummy AUTO_COMPRESS=FALSE PARALLEL=1")
  File "/opt/python/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 582, in execute
    data = sf_file_transfer_agent.result()
  File "/opt/python/lib/python3.8/site-packages/snowflake/connector/file_transfer_agent.py", line 705, in result
    Error.errorhandler_wrapper(
  File "/opt/python/lib/python3.8/site-packages/snowflake/connector/errors.py", line 224, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/opt/python/lib/python3.8/site-packages/snowflake/connector/errors.py", line 179, in default_errorhandler
    raise error_class(

**Comment by sfc-gh-yixie** [comment]
We'll look into this.

**Comment by sfc-gh-mkeller** [comment]
@ihatec0d1ng There's something wrong in the information you posted. Your `pip freeze` says that you have `snowflake-connector-python==2.7.0` but then the stack trace says `  File "/opt/python/lib/python3.8/site-packages/snowflake/connector/remote_storage_util.py", line 149, in upload_one_file`. However; the file `remote_storage_util` doesn't exist since `2.6.0` it was moved in [this commit](https://github.com/snowflakedb/snowflake-connector-python/commit/18ef9c06bd7900581520cebbe603c1cecb21509f#diff-4907bd05d2161f1ad720bcd42b9726bcf9746586081ecfb1e080b4e5db9c1b79).

The usage of `remote_storage_util` just means that you are uploading to a remote location (which a Snowflake stage is).
We absolutely don't try to detect where files are actually located. Everything we do with local files for uploading can be found [here](https://github.com/snowflakedb/snowflake-connector-python/blob/7e56243ff93992a26ffd861abafc3f96f60cc835/src/snowflake/connector/storage_client.py#L396).

If I had to guess whatever library you use for mounting the storage doesn't allow you to seek and read freely. The only thing I know that could cause this is if the fuse library doesn't implement the necessary actions. Please advise us on how this is setup? Is it done by Lambda automatically, if so how do you setup your lambda?
A way to verify this would be to write a small python script that does the same file actions that our library uses and run that.
