### ISSUE TITLE
SNOW-705495: Passing dtypes to fetch_pandas_all() and fetch_pandas_batches() API

### ISSUE THREAD

**Issue by yuvanist** [snowflakedb/snowflake-connector-python#1369]
## What is the current behavior?

Currently, fetch_pandas_all() assumes the dtype of the pandas dataframe from the first batch (This is the behavior of Pyarrow as well).  Now let's say there are 100K records and the records got batched into 20K of each, There exists a column that has all of them as null values, except for 10K records.
Now the fetch_pandas_all() API is breaking saying that

`arrow failed to build table from batches, errorInfo: Schema at index 9 was different:`

## What is the desired behavior?

After the ability to pass dtypes, this issue should be sorted. Since we can specify that it is of column Integer or other type and not of NULL type.

## How would this improve `snowflake-connector-python`?

Makes the fetch_pandas_all() API more robust.

**Comment by JakobAgeras** [comment]
I completely agree with that ! Currently I can't fetch some data since  I hae some time-columns which in some-batch is inferred as ns and other as us, casting that error.

TBH; I can't really see why you shouldn't allow the user to define that, or somehow have an "infer_dtype:bool" paramter to be set.
