### ISSUE TITLE
SNOW-719260: COPY INTO not accepting binded parameter

### ISSUE THREAD

**Issue by mariob316** [snowflakedb/snowflake-connector-python#1382]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   Python 3.10

2. What operating system and processor architecture are you using?

   MacOS M1

3. What are the component versions in the environment (`pip freeze`)?

   snowflake-connector-python: 2.8.1

4. What did you do?

  Trying to bind the table name in a `COPY INTO` query.
  ```
execution = client.execute(
	"""
	    COPY INTO %(table_name)s
	    FROM %(staged_file)s
	    file_format = (type = csv, skip_header = 1, FIELD_OPTIONALLY_ENCLOSED_BY ='"')
	""",
	params={"staged_file": staged_file, "table_name": f"{db_name}.FILES"},
	)
  ```

5. What did you expect to see?

   No query errors when binding parameters

Getting error:
```
001003 (42000): 01a92448-0506-604a-0000-d12933184f92: SQL compilation error:
syntax error line 2 at position 29 unexpected ''@STAGE/FILE.csv.gz''.
```
Query looks something like 
`running query [COPY INTO 'TABLENAME.FILES' FROM '@STAGE/FILE.csv.gz'...]`

If I hardcode `table_name` it works as expected.  It also works If I use python string formatting, which I rather avoid.

**Comment by sfc-gh-aling** [comment]
@mariob316, thanks for reaching out.

This is actually a known issue similar to https://github.com/snowflakedb/snowflake-connector-python/issues/10.
It is because object names are not supported for parameter binding. The `@STAGE/FILE.csv.gz` is taken as a string value instead of an identifier, and will be single quoted when bound.

As an alternative, you could try using `qmark` style to bypass the issue as guided here: https://docs.snowflake.com/en/user-guide/python-connector-example.html#qmark-or-numeric-binding.

We will consider adding the support for `pyformat` binding objects.

**Comment by mariob316** [comment]
@sfc-gh-aling Ahh, thanks for the link and explanation, it makes sense now! 
I will definitely try with `qmark` and keep an eye out for future support.

Thanks again

**Comment by ThomasThelen** [comment]
Just curious - was this implemented (and hence the issue closed)?
