### ISSUE TITLE
SNOW-894875: 2023 Snowflake Client Driver deprecation for GCP customers - clarification

### ISSUE THREAD

**Issue by edge7** [snowflakedb/snowflake-connector-python#1699]
Hi,
I have a  question about [this](https://community.snowflake.com/s/article/faq-2023-client-driver-deprecation-for-GCP-customers).
The document talks about:
`Historically, signed (or more commonly presigned) URL API requests to Snowflake GCP buckets, only required the payload to be signed (with SigV4).  However, currently, Google requires both the request headers and payload to be signed.`

And in particular, it states that the minimum Python Snowflake connector should be **2.7.8**

I see that GCS Downscope Token has been merged https://github.com/snowflakedb/snowflake-connector-python/pull/542, so it is available since:

```
v2.3.7(December 10,2020)
Added support for upcoming downscoped GCS credentials.
```

Can I have a bit of clarity?
I have 2.7.4 and cannot upgrade (as am using Python 3.6 and cannot upgrade). that is the reason why I am asking.

thanks

**Comment by sfc-gh-mkeller** [comment]
@edge7 We suggest upgrading to a newer Python version (newest versions support 3.8 and above) and the newest `snowflake-connector-python` version possible. This is because there were bugs in the implementation both in `2.7.8` and `2.7.4` that were fixed since.

That being said I was able to put and get files with `2.7.4` with Python 3.6. I'll post what I did to get this to work, but please note that we will not officially support any issues you may encounter:
1. You need to patch the version number to `2.7.8, or newer. Our server-side needs this to enable downscoped tokens to be supported. You can do this by either actually modifying the source-code in [version.py](https://github.com/snowflakedb/snowflake-connector-python/blob/v2.7.4/src/snowflake/connector/version.py), or provide `internal_application_version="2.7.8"` to the `snowflake.connector.connect` method.
2. I had to back-port the following PR https://github.com/snowflakedb/snowflake-connector-python/pull/1488 , particularly the 1 line change in `gcs_storage_client.py`.
3. I had to change the [following line](https://github.com/snowflakedb/snowflake-connector-python/blob/fedaa37fd1c39ad2884de78575377405675fb6fd/src/snowflake/connector/storage_client.py#L340) this way:
```diff
-            fd.truncate(self.meta.src_file_size)
+            fd.truncate(int(self.meta.src_file_size))
```
Once you make these changes you should be able to build your own Python 3.6 wheel.

**Comment by edge7** [comment]
hi @sfc-gh-mkeller 
thanks for your reply, I've been able to do that.

Do you have any suggestion about which Snowflake operations I could run, to test it?

Thanks a LOT
