### ISSUE TITLE
SNOW-1486242: Is this repo related to snowsql?

### ISSUE THREAD

**Issue by grepwood** [snowflakedb/snowflake-connector-python#1977]
I'm asking because I need SnowSQL, but I found a number of issues with it:
- after upgrading to RHEL 9, it doesn't work
- on the face of it, it's because it now requires libcrypto.so.1, which should be added to the list of dependencies of the RPM file*
- I check what the package even has that depends on legacy OpenSSL and turns out it's because snowsql comes with its own Python interpreter (3.8) which is dynamically linked to legacy OpenSSL
- I tried to replace libpython3.8.so.1.0 with a symlink to the system-provided libpython (3.9) and got several issues, but mostly that encodings library is missing

As such I would like to ask
- Where do I file bugs for SnowSQL? It seems it's a closed-source project
- Is this project related to SnowSQL or better yet, does it provide the same functionality? Because if yes then I'd like to drop SnowSQL like a hot potato and just use this

*I know that packaging software can be hard so here's a protip - always run `objdump -p | grep NEEDED` for each ELF that you're going to include in the package so you capture all the packages that are required below the scope of calling `dlopen`. `dlopen` is a very reliable footgun for package maintainers.

**Comment by sfc-gh-dszmolka** [comment]
hey and thank you for this question. trying to answer:
1. SnowSQL is meant to be used as a easy to use CLI interface and it heavily depends (== built on top of) on this library, the PythonConnector. 

The SnowSQL part (the CLI itself) is indeed built from closed-source. If you wish to file bugs related to SnowSQL, you can still do so - please login to your Snowflake account and [open a case with Snowflake Support](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge)

Before doing so, please make sure you can reproduce those bugs on the latest version, if possible. It might be already fixed what you're seeing. (if it's related to Python 3.8 as you mentioned, then it's probably still unfixed because the latest SnowSQL still uses Python 3.8.18)

To add some extra flavor, we have another CLI called [snowcli / snowflake-cli](https://github.com/snowflakedb/snowflake-cli) which again, might or might not fit your use-case. 

Appreciate the advice too!

2. You should indeed be able to do everything and more, by only using the pure PythonConnector (this library where you filed this issue) without SnowSQL.
SnowSQL is really meant for those users and use-cases where someone needs a readily available and usable CLI application to query Snowflake from a non-GUI manner.

Hope this answers the question but let us know if you have more

**Comment by grepwood** [comment]
> Before doing so, please make sure you can reproduce those bugs on the latest version, if possible. It might be already fixed what you're seeing. (if it's related to Python 3.8 as you mentioned, then it's probably still unfixed because the latest SnowSQL still uses Python 3.8.18)

This is happening on SnowSQL 1.3.0 which afaik is the latest version. If the RPM requires the .so name instead of a package name, that will introduce enough ambiguity that yum/dnf should resolve it to whatever comes up from `yum whatprovides libcrypt.so.1`. On RHEL8 and RHEL9 it's two different package names that provide this, for obvious reasons - RHEL9 is using OpenSSL 3 as the default openssl package.

Thank you very much! I'll try and use this project instead :)
