### ISSUE TITLE
Current version too big for AWS Lambda - make pyarrow and other non 'core' functionality optionally installed

### ISSUE THREAD

**Issue by braunreyes** [snowflakedb/snowflake-connector-python#213]
We are using Python 3.7.4 running the 2.0.1 version of the connector
Local environments use MacOS and Production environments use alpine, debian based, and amazon linux based OS environments.

I believe that some of the larger components of this library should be optionally deployed as extras.  Similar to how projects like airflow handle it.

We have an app running a 1.7 version of the connector and the package size was about 80 MB, now with things like pyarrow, the package is close to 380MB and cannot be used with AWS Lambda.

I could not see away to prevent certain dependencies from being deployed with out manually deleting from the venv.

Please advise if this is something that can get some exposure or if there are other workarounds you have to keep the installed package small enough for AWS lambda.

AWS Lambda has package limit of 250MB

**Comment by smtakeda** [comment]
We are working on this.

**Comment by smtakeda** [comment]
Other workaround I heard was after installing 2.0.1 and uninstall pyarrow.

**Comment by smtakeda** [comment]
v2.0.2 will have the fix. ETA is next week.

**Comment by aleGpereira** [comment]
I was just dealing with this problem. Thank you guys for fixing this issue. Will use 1.9.1 for now.

**Comment by smtakeda** [comment]
v2.0.2 is released.

**Comment by thosieucoi** [comment]
@smtakeda I have the same issue with v2.3.3
Would you please take a look?

**Comment by hiattp** [comment]
It looks like larger dependencies like pyarrow were pulled out of the connector itself but are non-optional if you want to include pandas, even though pyarrow is an optional dependency for pandas. Is it possible to make pyarrow similarly optional while still including pandas with the connector? We're having the exact same Lambda memory issue that was addressed in 2.0.2 with the added requirement of wanting to use pandas as well (while apparently not needing any pyarrow functionality afaict). Pyarrow is particularly troublesome since it clocks in around 230Mb by itself, leaving only 20Mb for anything else in Lambda 😬. Thanks in advance!
