### ISSUE TITLE
1.9.0 is no longer on pypi

### ISSUE THREAD

**Issue by erikselin** [snowflakedb/snowflake-connector-python#216]
It seems 1.9.0 has been pulled from pypi. This will break any pipeline and build processes that is version locked to 1.9.0 (with an asn1crypto lock to make it work). Please don't pull things from pypi, especially not versions that have been released for a considerable amount of time.

**Comment by smomen** [comment]
same experience here this morning, multiple project builds broke with this removal.

**Comment by dave-om1** [comment]
notice that the release notes for 1.9.1 and 2.0.1 are both this:
`Add asn1crypto requirement to mitigate incompatibility change.`
maybe a mistake?
however you slice it, no bueno

**Comment by ankit-bhatnagar167** [comment]
Background:
Python Connector v1.9.0 was removed because it did not pin the asn1crypto version resulting in several customers breaking when they upgraded the asn1crypto library to version 1.0.0. asn1crypto removed an API that is currently used by the Snowflake Python Connector

Impact:
Customers who have pinned a dependency on this package will receive a build error similar to:
Snowflake Python connector version 1.9.0 not found

Solution:
Customers should use 1.9.1 which properly pins the supported asn1crypto versions. 

pip install -U snowflake-connector-python==1.9.1

Additional Notes:
Python Connector v2.0.0 is impacted by the same issue as 1.9.0 and should be avoided
Python Connector v2.0.1 can be used but may break lamda deployments since the package size is over 200MB. The large size is due to inclusion of some optional libraries that are in Private Preview and not needed for normal operation.
Python Connector v2.0.2 will be released shortly with a much smaller package size.
Snowflake will not remove python versions in the future without proper notification to our customers.

**Comment by erikselin** [comment]
@ankit-bhatnagar167 thanks for the feedback.

Sorry to be frank here, but this is not a good way to release a patched version. What Snowflake has done here is break every production pipeline or build process that had the snowflake connector and asn2crypto pinned to `1.9.0` and `0.24.0`. Many Snowflake customers using a proper `pip freeze` or equivalent dependency management could fall into this group. A lot of perfectly fine, working code likely got broken because Snowflake removed this from PyPI.

A much better solution would have been to release 1.9.1 and 2.0.1 with the fixes and leave 1.9.0 and 2.0.0, as is, in PyPI. That would ensure nothing that is currently working breaks, and for anyone with broken stuff, there would be an update to fix their issue.

Generally, it is asking for trouble to remove packages once they have been released.

**Comment by ankit-bhatnagar167** [comment]
Noted @erikselin . 
I am keeping this issue open for a couple of days so anyone facing this issue can refer to it and get the details.

**Comment by hkapre** [comment]
@erikselin Your point is well taken. We will not be removing versions in the future.
