### ISSUE TITLE
Why was boto3 pinned below 1.4.8?

### ISSUE THREAD

**Issue by sethwoodworth** [snowflakedb/snowflake-connector-python#43]
Initially, in [this commit](https://github.com/snowflakedb/snowflake-connector-python/commit/213c63c49eea65f803c00116e4a840cbd461db6c) boto3 was pinned below `1.5.0`.  Then in a subsequent commit it was reduced to `<=1.4.7`.  This threw some errors in Pipenv and I was curious what the limitation is.

**Comment by smtakeda** [comment]
Since boto3 1.4.7 depends on botocore >=1.7.0,<1.8.0:
https://github.com/boto/boto3/commit/9d5fac2a36a31b9665a8d80c7dfe8df9fac4ceb3

I was afraid you may get incompatible combinations of boto3 and botocore if the newer version of boto3 (apparently 1.4.8 was just released) depends on newer botocore, e.g., botocore>=1.8.0,<1.9.0:
https://github.com/boto/boto3/commit/629a581de0407873b810613c49f8f1523106a18f

In fact, if I just relax boto3 to <1.5.0 today and install it, I got this:
```
>pip list | grep boto
boto3 (1.4.8)
botocore (1.7.48)
```
though botocore must be >1.8.0.

I could relax botocore at the same time, but there is a breaking change risk when the minor version is changed.

Will update `setup.py` for boto3 1.4.8 anyway.

**Comment by smtakeda** [comment]
https://github.com/snowflakedb/snowflake-connector-python/commit/7886a57eb36baf6f056d1818747a810a0c1d4ba2

Will push 1.4.13 this Thursday.

**Comment by smtakeda** [comment]
https://github.com/snowflakedb/snowflake-connector-python/releases/tag/v1.4.13 is out.

**Comment by RonRothman** [comment]
@smtakeda Forgive me for resurrecting an old thread (and let me know if you prefer a new one), but I didn't understand this comment:

> I could relax botocore at the same time, but there is a breaking change risk when the minor version is changed.

My understanding is that minor changes, by definition, are not breaking changes. Would you mind clarifying your concern there?

(How I got here: The upperbounding of boto3/botocore is preventing us from upgrading those libraries, and I came searching for an answer.)

**Comment by smtakeda** [comment]
@RonRothman, Snowflake Python connector depends on botocore's vendored `requests` package, which was deprecated a couple month back and likely to be removed in the near future, so I'm cautious about removing the upper bound limit... Yet it is not guaranteed patch version update won't remove it, though, that's all we can do the best.

Looks like `botocore` is 1.12.x, still has `vendored/requests`. That's good news to us, so will I do update the upper bound limit.

**Comment by smtakeda** [comment]
oh, wait the upperbound is already
```
        'botocore>=1.5.0,<1.13.0',
```

**Comment by RonRothman** [comment]
@smtakeda Ah, I see, thank you. [Found it](https://github.com/snowflakedb/snowflake-connector-python/blob/master/network.py#L20)!

But then I don't understand: why choose to use botocore's version of requests, instead of importing your own? I'm not seeing what the upside of this coupling is (thought I do see its downside).

**Comment by smtakeda** [comment]
@RonRothman mainly because the OCSP check monkey patch:
https://github.com/snowflakedb/snowflake-connector-python/blob/master/network.py#L69
It leverages pyOpenSSL, but the newer version of `requests` doesn't have the hook.
So we are investigating how we can migrate it to the regular requests when `botocore` drops it...

**Comment by RonRothman** [comment]
Got it--thanks for the explanation!
