### ISSUE TITLE
SNOW-203642: ERROR: Could not build wheels for snowflake-connector-python which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by mp082427** [snowflakedb/snowflake-connector-python#469]
I am trying to install snowflake-connector in anaconda prompt by using the below statement

pip install snowflake-connector-python[pandas]

or

pip install --upgrade snowflake-connector-python

I am getting the below error 
as
EERROR: Could not build wheels for snowflake-connector-python which use PEP 517 and cannot be installed directly

**Comment by sfc-gh-mkeller** [comment]
Hi @mp082427 ,
What OS and Python version are you using?

**Comment by mp082427** [comment]
> Hi @mp082427 ,
> What OS and Python version are you using?
I have installed Anaconda with Python 3.8.3 version in Windows 10 OS, and I have opened Anaconda Prompt and given the command from snowflake documentation  

pip install --upgrade snowflake-connector-python

And then I am seeing the error as
 error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for snowflake-connector-python
Failed to build snowflake-connector-python
ERROR: Could not build wheels for snowflake-connector-python which use PEP 517 and cannot be installed directly


Can some one help me

**Comment by sfc-gh-mkeller** [comment]
I'm sorry @mp082427 but we don't currently support Windows with Python 3.8.
Please use Python 3.7, or 3.6

**Comment by mp082427** [comment]
> I'm sorry @mp082427 but we don't currently support Windows with Python 3.8.
> Please use Python 3.7, or 3.6

you mean snowflake-connector-python does not support python 3.8.3

**Comment by keller00** [comment]
In specific the combination of windows and Python 3.8 is not supported.

**Comment by wxianxin** [comment]
I mean 3.9 is out already, and we still cannot fix support for 3.8? I am totally cool with it. The issue happens when supporting my package to my colleagues. Many of my colleagues have upgraded their environment and configuration of 3.8. No one would bother to create a new environment just to be compatible with my package. I am not blaming the maintenance here. Rather I am surprised Snowflake as a company is not testing their packages for latest python version. A multi-billion dollar tech company cannot support latest technology? You guys should begin testing for python Alphas, not lacking support for a whole 3.x release.

**Comment by sfc-gh-mkeller** [comment]
I'm sorry for the inconvenience @wxianxin 
But if you are mainly a Windows developer maybe you could help us out with your expertise.
Our issue with Windows and Python 3.8 seems to be originating from https://docs.python.org/3/whatsnew/3.8.html#ctypes

We think that it is because either our built `ddl` file, or the `ddl` file taht we include from pyarrow is not being properly found on Windows. The issue is also tricky, because it will only show itself when running some code paths, not at build time.

I can give building with Python 3.8 and Windows another go, but I am not an expert of this combination. Have you ran into this issue yourself?

**Comment by sfc-gh-mkeller** [comment]
You will be happy to know that Python 3.8 on Windows is now supported as of https://github.com/snowflakedb/snowflake-connector-python/commit/e2fd82758d02a6dc1f2cfcee972e2cf724f4d2b9
Next release should have wheels for 3.8 Windows! 🎉
