### ISSUE TITLE
SNOW-216954: Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [snowflakedb/snowflake-connector-python#520]
**Summary**
Installing snowflake-connector-python on aarch64 via pip using command "pip3 install snowflake-connector-python" tries to build wheel from source code

**Problem description**
snowflake-connector-python doesn't have wheel for aarch64 on PyPI repository. So, while installing snowflake-connector-python via pip on aarch64, pip builds wheel for same resulting in it takes more time to install snowflake-connector-python. Making wheel available for aarch64 will benefit aarch64 users by minimizing snowflake-connector-python installation time.

**Expected Output**
Pip should be able to download snowflake-connector-python wheel from PyPI repository rather than building it from source code.

@snowflake-connector-python-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make snowflake-connector-python wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by sfc-gh-mkeller** [comment]
Hey @odidev until we have a reliable Arm CI environment we wouldn't be able to test, or release The connector with confidence for ARM.
Do you know how other projects do this?

**Comment by diwms** [comment]
How we can help here? snowflake-connector cannot be installed on M1 Mac
Does it make sense to integrate something like https://github.com/uraimo/run-on-arch-action ?

**Comment by xhochy** [comment]
For the conda-forge packages, we use `drone.io` for builds on Linux/ARM64 and use cross-compilation for the Apple ARM64 packages. Happily using the `snowflake-python-connector` already on both 👍

**Comment by diwms** [comment]
> For the conda-forge packages, we use `drone.io` for builds on Linux/ARM64 and use cross-compilation for the Apple ARM64 packages. Happily using the `snowflake-python-connector` already on both 👍

Could you please share how you setup everything? Have no idea how to get working `snowflake-python-connector` on Apple ARM64 M1 :(

**Comment by groodt** [comment]
This issue is going off topic. Apple Silicon M1 is *not* the same thing as linux aarch64, which is the subject of this issue.

@sfc-gh-mkeller depending on what Snowflake is using for CI and how conventionally it is packaged, [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) is good option. I know that [scikit-learn is using it](https://github.com/scikit-learn/scikit-learn/blob/8ea176ae0ca535cdbfad7413322bbc3e54979e4d/build_tools/github/build_wheels.sh)

fwiw, it should also help with the Apple Silicon problem: https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon

@diwms If you upgrade to the latest version of `pip`, you should be able to use existing wheels for macos through Rosetta. Even through Rosetta, it's actually fast. Apple has done a good job. This is the best option while waiting for the ecosystem to publish `universal2` or wheels specific for Apple Silicon.
