### ISSUE TITLE
SNOW-249391:  issue with fetching data with connector and a special char

### ISSUE THREAD

**Issue by shgoren** [snowflakedb/snowflake-connector-python#574]
Hi,
I am encountering a problem with fetching data with a special character.
The error happens when using fetch_pandas_all() as well as when using fetchmany()

Error when using fetch_pandas_all():
`ArrowException: Unknown error: Wrapping Syn� vim Healthcare Solutions, Inc. failed`
 
Error when using fetchmany():
`InterfaceError: 252005: None: Failed to convert current row, cause: <class 'UnicodeDecodeError'> returned a result with an error set
` 

I narrowed down the error to a single row and col and I tried to use conversion to see what this character is:
![image](https://user-images.githubusercontent.com/34242458/102479489-a2149880-4067-11eb-8e0f-3e30fa1fa3e1.png)

I would really appreciate any help on that

package versions:
   snowflake-connector-python==2.3.6
   snowflake-sqlalchemy==1.2.4
   pyarrow==0.17.1
running on Linux-4.4.0-173-generic-x86_64-with-debian-stretch-sid
with python 3.6.5

**Comment by benjaminsingleton** [comment]
I've encountered the same issue due to special characters in a varchar field.

My current workaround, which isn't sustainable, is to create a fresh conda environment with `pandas==1.1.4` and `snowflake-connector-python==2.2.10` installed. The important thing is to not install the `[pandas]` extra for the `snowflake-connector-python` package. When PyArrow is not installed, we don't encounter the error.

Steps to recreate:
```
$ conda create --name egor
$ pip install pandas==1.1.4 snowflake-connector-python==2.2.10
```

**Comment by sfc-gh-mkeller** [comment]
Could you please post the data from that row @shgoren ?

**Comment by nikeshnaik** [comment]
Same use case, we have many special characters in snowflake data and while fetching it throws segmentation fault on the python client side. Tried without pandas but the bug still exists. Any workaround.?

**Comment by xhochy** [comment]
`pyarrow` does only support UTF-8 characters in strings. You could try either fetching it as a binary field or convert your native encoding on selection in the database to UTF-8.

**Comment by nikeshnaik** [comment]
native encoding is utf-8 in the database which makes this all odd. 
**Here's traceback:** 
```
  File "src/snowflake/connector/arrow_result.pyx", line 120, in snowflake.connector.arrow_result.ArrowResult.__next__
  File "src/snowflake/connector/arrow_iterator.pyx", line 216, in snowflake.connector.arrow_iterator.PyArrowIterator.__next__
  File "/home/user/.pyenv/versions/hsapi/lib/python3.7/site-packages/snowflake/connector/errors.py", line 224, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/user/.pyenv/versions/hsapi/lib/python3.7/site-packages/snowflake/connector/errors.py", line 186, in default_errorhandler
    cursor=cursor)
snowflake.connector.errors.InterfaceError: 252005: Failed to convert current row, cause: 'utf-8' codec can't decode byte 0xc9 in position 15: invalid continuation byte

```

**Comment by xhochy** [comment]
Maybe Snowflake itself is more resilient against errorneous UTF-8 data, `pandas` / `Python` seems to check for its validity.

**Comment by fhoffa-snow** [comment]
Related work-around:

https://stackoverflow.com/a/66463118/132438

Select `select hex_encode(string)` so you can de-encode with freedom on the Python side (`bytes.fromhex(col)`).

**Comment by kishvanchee** [comment]
@fhoffa-snow the linked SO answer worked for me too. At the same time I decoded using `latin-1`. I just ended up searching that character online and found it was latin. Hope it helps others.

**Comment by architsingh15** [comment]
This issue still exists, i just ran into it too. there was a special character stored in my snowflake table, when I tried to fetch that in dataframe i run into this error.

Do we have any ETA on this?

**Comment by gartho** [comment]
What is the status of this issue? I've just run into the same problem. I've using the documented python connector and it's dependencies as described in the installation notes, and using the provided sample data results in sporadic issues relating to the ArrowException.

Is the issue with the Snowflake demo data, or an issue with the Python connector framework?

**Comment by sfc-gh-aling** [comment]
hey folks, thanks for your patience, we got some updates for you.

We have located the issue -- it's within the Snowflake demo data some of which is encoded in `latin-1` instead of `utf-8`. Our Python connector is trying to decode the `latin-1` encoded bytes with `utf-8` leading to the decode error. This is not a connector issue but something went wrong with the sample data.

We're working with the sample data team to re-generate the database with the correct encoding. It will take some time to manipulate those tables while avoid any breakings to existing users, and populate the change to all deployments. I will keep you guys updated.

----- 

Here's some more context of the complete story and for future developers who might encounter similar issue:

Previously snowflake allow people to copy data into database using file without validating the encode being `utf-8` or not, which means data of non `utf-8` encoded could exist in the database if they were inserted long time ago.

However, this is not allowed any more which is announced in https://community.snowflake.com/s/article/VALIDATE-UTF8-File-Format-Option-Obsoleted.

As mentioned in the [COPY INTO TABLE reference doc](https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html): `Snowflake stores all data internally in the UTF-8 character set. The data is converted into UTF-8 before it is loaded into Snowflake.`.

So here's what I would recommend to do based on different scenarios if you have some old data in the database which is encoded in non-utf8, you could choose to either approach:
  - follow @fhoffa-snow's suggestion (thanks!) to hex_encode the data and decode by yourself
  - or set `snowflake.connector.cursor.CAN_USE_ARROW_RESULT_FORMAT` to `False`, which underlying uses JSON format for internal results. This approach works because on the service side, JSON format has special logic to handle and escape bytes. 
  - for long term, it's recommended to re-encode the database in `utf-8`, consider dumping the data, and re-importing them if possible.

new inserted data shall be good as all data will be converted to `utf-8` encoded by snowflake.

------

I wish this helps answer your questions. let me know if there's more I could help.

**Comment by sfc-gh-aling** [comment]
good news folks, the sample data has been re-encoded with `utf-8`, could you take a try?

**Comment by sfc-gh-aling** [comment]
I'm closing the issue now, feel free to reach out or reopen the issue if you have any other questions regarding to this topic.

**Comment by gartho** [comment]
I'm still seeing this issue - is there something we need to do with the sample data? Do tables need to be recreated?
