### ISSUE TITLE
SNOW-347580: Enable option to create tables (including temporary/transient option) when table doesn exist using write_pandas

### ISSUE THREAD

**Issue by manugarri** [snowflakedb/snowflake-connector-python#686]
## What is the current behavior?
write_pandas only works if the table already exists.

## What is the desired behavior?
We use temporary tables as intermediate stages and we create those tables on the fly via [snowconn.write_df](https://github.com/Daltix/snowconn/blob/master/snowconn/connect.py#L231)

We are considering moving to snowflake-connector write_pandas but it does not support our needs.

## How would this improve `snowflake-connector-python`?
We would be able to use write_pandas for intermediate steps in our ETL pipelines.

**Comment by lababidi** [comment]
@sfc-gh-mkeller I'm bumping this. Why would we need to create a table before uploading a pandas DF?

**Comment by sfc-gh-mkeller** [comment]
It was done this way, because for the connector to do this automatically we'd have to implement our own ORM that would parse `pandas.DataFrame`s and then generate queries that creates a table that can accept the data in the `pandas.DataFrame`.

This is the reason why we added https://github.com/snowflakedb/snowflake-connector-python/blob/61a06a1ed712a574883bc028ac3d5ab42ea80368/src/snowflake/connector/pandas_tools.py#L241
So that if you don't want to generate the table yourself you could have `SQLAlchemy` create it for you. Could you please check out if this worked for you while I explore different ideas with my team?

**Comment by sfc-gh-madkins** [comment]
@manugarri I just submitted this PR (https://github.com/snowflakedb/snowflake-connector-python/pull/898) that allows snowflake to infer the schema from parquet files that are staged during the write process of write_pandas. Snowflake has an INFER_SCHEMA table function that came out not too long ago.

**Comment by manugarri** [comment]
@sfc-gh-madkins  thanks, for what i see, the functionality you add on that PR is to create a new table if it doesnt exist, **not** to give the option to make that table temporary (which is a pretty common step in etls). Would that be the case?

**Comment by manugarri** [comment]
@sfc-gh-madkins  any update on this?

**Comment by sfc-gh-madkins** [comment]
@manugarri we are still talking internally the best way to support this. If you look at the current PR, it calls for defining the table type and if the table doesnt exist, create a new one.

**Comment by malav-doshi** [comment]
+1 to the original request. I would like to be able to specify if I want to append data to the table, create/replace

**Comment by franciscojavierarceo** [comment]
+1 as table creation is a very useful and common pattern to pass as a parameter argument.
